routes/web.php
<?php

use App\Http\Controllers\DoctorController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\PolyclinicController;
use App\Http\Controllers\RegistrationController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Models\Menu;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

View::composer('layouts.static.navbar', function ($view) {
    $menus = Menu::with('parent', 'child')->where('parent_id', '=', 0)->get();
    $view->with('menus', $menus);
});

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function () {
    // route for datatable server-side
    Route::get('users/getUsersAjax', [UserController::class, 'getDataAjax']);
    Route::get('roles/getRolesAjax', [RoleController::class, 'getDataAjax']);
    Route::get('permissions/getPermissionsAjax', [PermissionController::class, 'getDataAjax']);
    Route::get('menus/getMenusAjax', [MenuController::class, 'getDataAjax']);
    Route::get('patients/getPatientsAjax', [PatientController::class, 'getDataAjax']);
    Route::get('doctors/getDoctorsAjax', [DoctorController::class, 'getDataAjax']);
    Route::get('polyclinics/getPolyclinicsAjax', [PolyclinicController::class, 'getDataAjax']);

    // route group register/getRegistsAjax, etc.
    Route::prefix('register')->name('register.')->group(function () {
        Route::get('slip', [RegistrationController::class, 'slip'])->name('slip');
        Route::get('getRegistsAjax', [RegistrationController::class, 'getDataAjax']);
        Route::get('getDataPolyAjax', [RegistrationController::class, 'getDataPolyAjax']);
        Route::get('getPatientBy', [RegistrationController::class, 'getPatientBy']);
        Route::get('getDoctorsBy', [RegistrationController::class, 'getDoctorsBy']);
        Route::get('getSchedulesBy', [RegistrationController::class, 'getSchedulesBy']);
    });

    // route for resource CRUD
    Route::resource('users', UserController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('permissions', PermissionController::class);
    Route::resource('menus', MenuController::class);
    Route::resource('patients', PatientController::class);
    Route::resource('doctors', DoctorController::class);
    Route::resource('polyclinics', PolyclinicController::class);
    Route::resource('register', RegistrationController::class);
});

resources/views/regist/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="page-content">
        <div class="container-fluid">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-dismissible alert-label-icon label-arrow fade show" role="alert">
                    <i class="mdi mdi-check-all label-icon"></i>{{ $message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            @endif

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0 font-size-18">{!! $data['heading'] !!}</h4>
                        <a href="{{ route('patients.create', ['from' => 'registrasi']) }}" class="btn btn-primary"><span class="fas fa-user-plus"></span> Pasien Baru</a>
                        <a href="{{ route('register.create') }}" class="btn btn-secondary"><span class="fas fa-user-plus"></span> Pasien Lama</a>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="{{ url('dashboard') }}">Dashboard</a></li>
                                <li class="breadcrumb-item active">{!! $data['heading'] !!}</li>
                            </ol>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">{!! $data['card_title'] !!}</h4>
                            <p class="card-title-desc">{!! $data['card_title_desc'] !!}</p>
                        </div>
                        <div class="card-body">
                            @if (!empty($data['notif']))
                                {{-- Notif --}}
                                <div class="alert alert-{!! $data['notif']['label'] !!} alert-dismissible
                                    alert-label-icon label-arrow fade show mb-0" role="alert">
                                    <i class="{!! $data['notif']['icon'] !!} label-icon"></i>
                                    {!! $data['notif']['message'] !!}
                                </div>

                                <br>
                            @endif

                            <table id="datatable" class="table table-bordered dt-responsive nowrap w-100">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>No RM</th>
                                        <th>Nama Pasien</th>
                                        <th>Antrian</th>
                                        <th>Poliklinik</th>
                                        <th>Tipe Bayar</th>
                                        <th>Penjamin</th>
                                        <th>Tgl Registrasi</th>
                                        <th>Status</th>
                                        <th width="80px">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end page title -->
        </div> <!-- container-fluid -->
    </div>

    <script>
        $(function () {
            // server-side datatable
            var table = $('#datatable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ url('register/getRegistsAjax') }}",
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
                    {data: 'no_rm', name: 'patient.no_rm'},
                    {data: 'pasien', name: 'patient.nama'},
                    {data: 'antrian', name: 'antrian'},
                    {data: 'poli', name: 'polyclinic.nama'},
                    {data: 'tipe_bayar', name: 'tipe_bayar'},
                    {data: 'penjamin', name: 'penjamin'},
                    {data: 'tgl_registrasi', name: 'tgl_registrasi'},
                    {data: 'status', name: 'status'},
                    {data: 'actions', name: 'actions', orderable: false, searchable: false},
                ]
            });

            // delete function
            // $('body').on('click', '.destroy', function () {
            //     var id = $(this).data("id");
            //     let _token = $('meta[name="csrf-token"]').attr('content');

            //     console.log(id);

            //     Swal.fire({
            //         title: "Are you sure?",
            //         text: "You won't be able to revert this!",
            //         icon: "warning",
            //         showCancelButton: true,
            //         confirmButtonColor: "#2ab57d",
            //         cancelButtonColor: "#fd625e",
            //         confirmButtonText: "Yes, delete it!"
            //     }).then(function (result) {
            //         if (result.value) {
            //             // delete data
            //             $.ajax({
            //                 type: "DELETE",
            //                 url: `/polyclinics/${id}`,
            //                 data: {_token: _token},
            //                 dataType: "JSON",
            //                 success: function (response) {
            //                     Swal.fire("Deleted!", "Your file has been deleted.", "success");

            //                     table.draw();
            //                 }
            //             });
            //         }
            //     })
            // });
        });

        $('#print-view').click(function (e) {
            e.preventDefault();
            console.log(e.target);
            // jQuery(e.target).attr('target', '_blank');
        });
    </script>
@endsection

resources/views/regist/slip.blade.php
@extends('layouts.print')

@section('content')
<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="invoice-title">
                        <div class="d-flex align-items-start">
                            <div class="flex-grow-1">
                                <div class="mb-4">
                                    <img src="{{ asset('images/logo-sm.svg') }}"
                                        alt="" height="24"><span
                                        class="logo-txt">{{ config('app.name', 'Laravel') }}</span>
                                </div>
                            </div>
                            <div class="flex-shrink-0">
                                <div class="mb-4">
                                    <h4 class="float-end font-size-16">Invoice
                                        # 12345</h4>
                                </div>
                            </div>
                        </div>

                        <p class="mb-1">1874 County Line Road City, FL 33566</p>
                        <p class="mb-1"><i class="mdi mdi-email align-middle
                                mr-1"></i> abc@123.com</p>
                        <p><i class="mdi mdi-phone align-middle mr-1"></i>
                            012-345-6789</p>
                    </div>
                    <hr class="my-4">
                    <div class="row">
                        <div class="col-sm-6">
                            <div>
                                <h5 class="font-size-15 mb-3">Billed To:</h5>
                                <h5 class="font-size-14 mb-2">Richard Saul</h5>
                                <p class="mb-1">1208 Sherwood Circle
                                    Lafayette, LA 70506</p>
                                <p class="mb-1">RichardSaul@rhyta.com</p>
                                <p>337-256-9134</p>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div>
                                <div>
                                    <h5 class="font-size-15">Order Date:</h5>
                                    <p>February 16, 2020</p>
                                </div>

                                <div class="mt-4">
                                    <h5 class="font-size-15">Payment Method:</h5>
                                    <p class="mb-1">Visa ending **** 4242</p>
                                    <p>richards@email.com</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="d-print-none mt-3">
                        <div class="float-end">
                            <a href="javascript:window.print()" class="btn
                                btn-success waves-effect waves-light mr-1"><i
                                    class="fa fa-print"></i></a>
                            <a href="#" class="btn btn-primary w-md
                                waves-effect waves-light">Send</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end row -->
</div> <!-- container-fluid -->
@endsection